### ISSUE TITLE
hotfix video

### ISSUE THREAD

**Issue by abdouheavydrive** [HeavyDrive/heavy-drive.com#41]
Revoir la taille de la video par rapport à la page pour qu'elle soit résponsive

**Comment by abdouheavydrive** [comment]
Revoir la taille de la video par rapport à la page, pour qu'elle soit résponsive

**Comment by LubinAshley** [comment]
https://developer.mozilla.org/fr/docs/Outils/Vue_adaptative pour tester la responsivité

**Comment by abdouheavydrive** [comment]
C'est fait pour la responsivité de la vidéo par rapport à la page d'acceuil, il reste juste la responsivité du slogan au milieu de la vidéo que j'ai pas pu faire
